### ISSUE TITLE
能否用博客和正式文档的方式表达你这个框架的使用

### ISSUE THREAD

**Issue by zhuewizz** [8treenet/freedom#11]

**Comment by 8treenet** [comment]
好的，可以。
example 其实基本表达了。

**Comment by zhuewizz** [comment]
谢谢你这么快回复我的问题，毕竟对ddd才接触，看到很多文章都是java c#的代码实例，推广开源项目
文档很重要！

**Comment by 8treenet** [comment]
好的，我会尽快的。
其实正在写。ddd比较抽象，文章需要列举复杂的场景，已经不是纯技术文档了。
感谢关注




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhuewizz"<notifications@github.com&gt;; 
发送时间: 2020年6月12日(星期五) 晚上6:08
收件人: "8treenet/freedom"<freedom@noreply.github.com&gt;; 
抄送: "4932004"<4932004@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [8treenet/freedom] 能否用博客和正式文档的方式表达你这个框架的使用 (#11)





 
谢谢你这么快回复我的问题，毕竟对ddd才接触，看到很多文章都是java c#的代码实例，推广开源项目
 文档很重要！

**Comment by zhuewizz** [comment]
另没有赞助的地方？，想向你表达敬意，毕竟在企业级应用的各方面，用golang的很少

**Comment by 8treenet** [comment]
谢谢谢谢，不需要的。我不是全职写。兼职的。哈哈。

**Comment by zhuewizz** [comment]
你这个朋友，很希望交，我下周会去北京，有机会能见上你！方便的话

**Comment by 8treenet** [comment]
我微信 4932004

**Comment by zhuewizz** [comment]
谢谢你，马上加！！！

**Comment by cameronhuang95** [comment]
我是不是第一个用这个项目做开发的小白鼠

**Comment by 8treenet** [comment]
不是第一个。
但不能否认的是用户确实不多。
我也不想搞这么高的门槛。
但我认为这些都是有意义的。











杨树&nbsp;Shu&nbsp;Yang
Tel:&nbsp;+8613513517944
Twitter:&nbsp;_CharlieYang
Website:&nbsp;http://www.8tree.net

---原始邮件---
发件人: "cameronhuang95"<notifications@github.com&gt;
发送时间: 2020年7月3日(周五) 凌晨0:47
收件人: "8treenet/freedom"<freedom@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"8treenet"<4932004@qq.com&gt;;
主题: Re: [8treenet/freedom] 能否用博客和正式文档的方式表达你这个框架的使用 (#11)




 
我是不是第一个用这个项目做开发的小白鼠

**Comment by cameronhuang95** [comment]
可以加你的微信吗。我看到上边有个微信号。

**Comment by 8treenet** [comment]
可以的






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cameronhuang95"<notifications@github.com&gt;; 
发送时间: 2020年7月3日(星期五) 下午3:56
收件人: "8treenet/freedom"<freedom@noreply.github.com&gt;; 
抄送: "4932004"<4932004@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [8treenet/freedom] 能否用博客和正式文档的方式表达你这个框架的使用 (#11)





 
可以加你的微信吗。我看到上边有个微信号。
 
&mdash;
