### ISSUE TITLE
能否增加支持grpc、es等

### ISSUE THREAD

**Issue by smallfish-root** [8treenet/freedom#35]
能否增加支持grpc、es等

**Comment by 8treenet** [comment]
grpc 有些小众了，暂时不考虑了。多语言技术栈下 Java Python PHP 这些团队貌似并不认同。
云原生 k8s istio 下的多语言用http通信更包容。




八叉树
***@***.***




------------------ 原始邮件 ------------------
发件人: smallfish-root ***@***.***&gt;
发送时间: 2021年4月20日 23:21
收件人: 8treenet/freedom ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[8treenet/freedom] 能否增加支持grpc、es等 (#35)





 
能否增加支持grpc、es等
