### ISSUE TITLE
关于数据库事务问题

### ISSUE THREAD

**Issue by licbin** [8treenet/freedom#36]
```
// FetchDB .
func (repo *Repository) FetchDB(db interface{}) error {
	resultDB := globalApp.Database.db

	transactionData := repo.worker.Store().Get(TransactionKey)
	if transactionData != nil {
		resultDB = transactionData
	}
	if resultDB == nil {
		return errors.New("DB not found, please install")
	}
	if !fetchValue(db, resultDB) {
		return errors.New("DB not found, please install")
	}
	// db = globalApp.Database.db.New()
	// db.SetLogger(repo.Worker.Logger())
	return nil
}

```

这里拿到的事务，在并发请求情况下是否也会拿取到其他请求的事务？

**Comment by charie10086** [comment]
不会，基础教程里已经强调了。 每一个请求都是基于worker 独立的对象 controller service repository




八叉树
***@***.***




------------------ 原始邮件 ------------------
发件人: licbin ***@***.***&gt;
发送时间: 2021年5月14日 10:14
收件人: 8treenet/freedom ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[8treenet/freedom] 关于数据库事务问题 (#36)





// FetchDB .func (repo *Repository) FetchDB(db interface{}) error {resultDB := globalApp.Database.dbtransactionData := repo.worker.Store().Get(TransactionKey)if transactionData != nil {resultDB = transactionData}if resultDB == nil {return errors.New("DB not found, please install")}if !fetchValue(db, resultDB) {return errors.New("DB not found, please install")}// db = globalApp.Database.db.New()// db.SetLogger(repo.Worker.Logger())return nil}
这里拿到的事务，在并发请求情况下是否也会拿取到其他请求的事务？

**Comment by licbin** [comment]
谢谢。看了遍源码理解了。

**Comment by 8treenet** [comment]
不用谢，主要思想还是Aop，中间的切面扩展能力。 可以基于Worker 设计infra 做很多事情

**Comment by Favoryoung** [comment]
有一点疑问 如果一次请求中并发操作数据库(虽然这样的操作并不常见)，是不是就有可能造成 db 的获取混乱？

**Comment by ccnot** [comment]
不可以。你直接开几个go操作事务 试试。或者试试别的多线程操作事务。不需要使用任何框架。












八叉树
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月9日(周六) 上午6:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [8treenet/freedom] 关于数据库事务问题 (#36)




 
有一点疑问 如果一次请求中并发操作数据库(虽然这样的操作并不常见)，是不是就有可能造成 db 的获取混乱？

**Comment by 8treenet** [comment]
不可以,这是最基本的。
你直接开几个go操作事务，不用任何框架 试试。
或者试试其他语言多线程操作事务。

**Comment by Favoryoung** [comment]
感谢回复！

> 不可以,这是最基本的。

这是说不能或者不推荐 在goroutine中操作数据库事务么？ 

我尝试运行多个goroutine 使用grom执行mysql事务，
在配置了连接池的情况下，起了2w个goroutine 执行事务,看起来结果也并没有问题。
```go
func main() {
	db, err := gorm.Open(mysql.Open("root:123456@tcp(localhost:3306)/test?charset=utf8mb4&parseTime=True&multiStatements=true"))
	if err != nil {
		panic(err)
	}
	sqlDB, err := db.DB()
	if err != nil {
		panic(err)
	}
	sqlDB.SetMaxOpenConns(100)

	var wg sync.WaitGroup
	for i := 0; i < 10000; i++ {
		go transactionSuccessInsert(db, &wg)
		go transactionFailInsert(db, &wg)
	}
	wg.Wait()
}

func transactionSuccessInsert(db *gorm.DB, wg *sync.WaitGroup) {
	wg.Add(1)
	db.Transaction(func(tx *gorm.DB) error {
		result := tx.Create(&userModel{
			Name: "Success",
		})
		return result.Error
	})
	wg.Done()
}

func transactionFailInsert(db *gorm.DB, wg *sync.WaitGroup) {
	wg.Add(1)
	db.Transaction(func(tx *gorm.DB) error {
		tx.Create(&userModel{
			Name: "Fail",
		})
		return errors.New("transactionFail")
	})
	wg.Done()
}
```

**Comment by 8treenet** [comment]
你这样当然没问题， 你这样是每个并发一个事务，这是1:1的
难道你的问题不是 多个并发下用一个事务吗？ 如果不是，这个问题我没get到。。。

**Comment by Favoryoung** [comment]
哦哦 我明白了， `FetchDB()` 方法的确比较优雅，使用的时候不用区分是不是事务 可以自动获取DB，但这也有一点缺陷就是无法并发操作数据库。我就是想表达这个意思~

**Comment by 8treenet** [comment]
这种场景用FetchOnlyDB去解决了。
