### ISSUE TITLE
如何实践依赖注入？

### ISSUE THREAD

**Issue by RanchoCooper** [8treenet/freedom#38]
理解了依赖倒置，但是不知道怎么进行DI。作者可以指明一下freedom中的做法吗？目前没找到框架是怎么进行依赖注入的

我自己做的项目现在通过依赖倒置完成了repo接口和repo实现，但是不知道怎么做DI，卡在这里了。希望解答下，感谢

**Comment by dawenxi5097484** [comment]
哦｀｀我正在忙，

**Comment by dvd3926561** [comment]
哦｀｀我正在忙，

**Comment by RanchoCooper** [comment]
why closed？
