### ISSUE TITLE
一级缓存的过期时间在哪里设置的

### ISSUE THREAD

**Issue by Zhyannan** [8treenet/freedom#45]
缓存组件里可以设置redis换成过期时间，一级的本地缓存过期时间不需要设置吗

**Comment by charie10086** [comment]
worker.Store() 一级缓存的生命周期是请求进入-请求结束。通常用于优化代码比如某个id(1001)在代码函数中传递，可能多个函数读取这个1001的模型。
&nbsp;


八叉树
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 下午4:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [8treenet/freedom] 一级缓存的过期时间在哪里设置的 (Issue #45)





 
缓存组件里可以设置redis换成过期时间，一级的本地缓存过期时间不需要设置吗

**Comment by Zhyannan** [comment]
这样的话，一个请求进来之后，从本地拿到缓存后，这个请求在结束之前，其他请求更新的缓存都不会生效了吗？

**Comment by ccnot** [comment]
简单的来说每个请求都有独立的字典，一级缓存使用的是该请求的字典。这个字典在请求进入的时候开辟，请求结束的时候释放。
其他请求不存在关系的。

&nbsp;


八叉树
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月23日(星期天) 下午4:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [8treenet/freedom] 一级缓存的过期时间在哪里设置的 (Issue #45)





 
这样的话，一个请求进来之后，从本地拿到缓存后，这个请求在结束之前，其他请求更新的缓存都不会生效了吗？

**Comment by 8treenet** [comment]
简单的来说每个请求都有独立的字典，一级缓存使用的是该请求的字典。这个字典在请求进入的时候开辟，请求结束的时候释放。
其他请求不存在关系的。

**Comment by Zhyannan** [comment]
这个组件看起来只能缓存单实体的，复合型的数据，比如前100条商品信息这样的是不是不支持，还得自己写

**Comment by 8treenet** [comment]
参考这个默认组件自己写即可。
